#!/bin/bash

PERSON1=$1
PERSON2=$2

echo "$PERSON1: HI $PERSON2"
echo "$PERSON2: HI $PERSON1, HOW ARE YOU?"
echo "$PERSON1: I'M GOOD $PERSON2"
echo "$PERSON2: WHAT ARE YOU GOING NOW $PERSON1"
echo "$PERSON1: I'M GOING X PROJECT"

