#!/bin/bash

FRUITS=("APPLE" "ORANGE" "MANGO" "BANANA")

echo " FIRST FRUIT IS : ${FRUITS[0]}"
echo " SECOND FRUIT IS : ${FRUITS[1]}"
echo " THIRD FRUIT IS : ${FRUITS[2]}"
echo "LIST OF FRUITS ARE: ${FRUITS[@]}"