#!/bin/bash

FRUITS=("APPLE" "BANANA" "MANGO" "GRAPES")

echo "FRIST FRUIT NAME IS: ${FRUITS[0]}"
echo "SECOND FRUIT NAME IS: ${FRUITS[1]}"
echo "THIRD FRUIT NAME IS: ${FRUITS[2]}"
echo "FOURTH FRUIT NAME IS: ${FRUITS[3]}"
echo "ALL FRUITS NAME IS: ${FRUITS[@]}"
